### ISSUE TITLE
Not compatible with Polymer 2

### ISSUE THREAD

**Issue by dejan9393** [PolymerElements/gold-cc-expiration-input#65]

**Comment by e111077** [comment]
This element is compatible with Polymer 2. Can you please explain what issues you are running into in regards to this?

**Comment by isahota** [comment]
It display like a paper input instead of the expiration date and doesn't allow input.

**Comment by notwaldorf** [comment]
I can't repro this: http://jsbin.com/bekokim/edit?html,output. Are you importing `gold-cc-expiration-input` correctly?

**Comment by isahota** [comment]
I am just running this command, bower install --save PolymerElements/gold-cc-expiration-input.  But, when it  imports, I do get the the following message, "Unable to find a suitable version for polymer" and it asks me to select from couple of different versions.

**Comment by e111077** [comment]
Hmm, this seems to be a dependency issue in your project. Seems like you might have a dependency that relies on polymer 1 and another on a polymer 2. My guess is that the element that is relying on the wrong version of polymer might be breaking and thus making this element not display correctly.

**Comment by jshortall** [comment]
I think the issue is with the tags on this repo. 

Using the recommended format for Polymer elements in bower.json does not work for this element - (PolymerElements/gold-cc-expiration-input#^2.0.0) because this element is tagged v2.0 while all the others are v2.0.0

I was able to get it to install by using PolymerElements/gold-cc-expiration-input#v2.0, but I'm guessing the repo should update it's tagging to match.

Hope that helps!

**Comment by isahota** [comment]
Thank you everyone for your reply.   I am able to install it in a new folder and it works fine.  There seems to be a version conflict with some other component I have installed in this project, so when I instill this component it does not work.  I'll have to figure out the conflict, fix it, which should fix this issue.

**Comment by notwaldorf** [comment]
Oh shit, our bad! I just release 2.0.0, hope this solves all the problems!
